server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-15-164-237-10.ap-northeast-2.compute.amazonaws.com:3306/likelion-db
    username: root
    password: password